/* eslint-disable @next/next/no-img-element */
import Image from 'next/image'

export default function GetCyborgApe() {
    return (
        <>
            <div className="flex flex-col-reverse md:flex-row px-12 md:px-20">
                <div className="md:w-1/4">
                    <img src="/img/teams/5.PNG" className="rounded-xl" alt="" />
                </div>
                <div className="md:w-3/4 md:ml-24 mb-8 md:mb-0 text-center md:text-left">
                    <h2 className="font-bold text-4xl">Benefit by Holding Cyborg Ape</h2>
                    <p className="mt-6 text-gray-500">
                        By purchasing Cyborg Ape Genesis you will get free mint for every our derivative project that affiliated with Cyborg Ape! <br />
                        <br /> You also get IP permission to all of our collection in the future, we will purchase MAYC and other project! <br />
                        <br /> Every Cyborg Ape Holders will get free NFT that generated by Mutant Ape Yacht Club character!
                    </p>
                </div>
            </div>
        </>
    )
}
